name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      
jobs:

  Conduit_Selenium_Tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start Conduit
        run: |
          docker-compose up -d
      
      - name: install Nodejs
        uses: actions/setup-node@v2 
        with:
          node-version: '14'

      - name: Install Selenium Side Runner
        run: |
          npm install -g selenium-side-runner

      - name: Install Chrome
        run: |
          sudo apt install google-chrome-stable

      - name: Install seleniumbase
        run: pip install seleniumbase 

      - name: Install chromedriver
        run: |
          seleniumbase install chromedriver

      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

      - name: Run Integration Tests
        run: |
          docker-compose up -d
          docker exec realworld_drash deno test -A --unstable tests/integration/test.ts
  
      - name: Run Unit Tests
        run: |
          docker-compose up -d
          docker exec realworld_drash deno test -A --unstable tests/unit/models/base_model_test.ts

      - name: Run Registration Tests 
        run: |
          selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, --headless, --nogpu]" seleniumide-tests/registration.side

      - name: Run Login Tests 
        run: |
          selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, --headless, --nogpu]" seleniumide-tests/login.side

      - name: Run Post Tests 
        run: |
          selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, --headless, --nogpu]" seleniumide-tests/post.side

#  linter:
#      # Only one OS is required since fmt is cross platform
#   runs-on: ubuntu-latest

#    steps:
#     - uses: actions/checkout@v2

#     - name: Install Deno
#       uses: denolib/setup-deno@master

#     - name: Formatter
#       run: deno fmt --check --unstable --ignore='src/public,src/vue,src/package.json,src/webpack.config.js'

#     - name: Linter
#       run: deno lint --unstable --ignore='src/public,src/vue,src/package.json,src/webpack.config.js'
